{% set data = load_setup_py_data() %}

package:
  name: "conda-minify"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  noarch: "python"
  entry_points:
    - conda-minify = conda_minify.__main__:main

requirements:
  build:
    - python >=3.4
    - setuptools
    - pyyaml >3.0
    - conda >=4.3.0
  run:
    - python >=3.4
    - conda >=4.3.0
    - pyyaml >3.0

test:
  imports:
    - conda_minify

about:
  home: https://github.com/jamespreed/conda-minify
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: "Tools for minimizing and relaxing Conda environment requirements for cross-platform sharing."
  dev_url: https://github.com/jamespreed/conda-minify