{% set data = load_setup_py_data() %}

package:
  name: "{{ data.name|lower }}"
  version: "{{ data.version }}"

source:
  url: "none yet"
  #sha256: 

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - conda >=4.3.0
    - pyyaml >3.0

test:
  imports:
    - conda_minify

about:
  home: https://github.com/jamespreed/conda-minify
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: "Tools for minimizing and relaxing Conda environment requirements for cross-platform sharing."
  dev_url: https://github.com/jamespreed/conda-minify